spring:

  docker:
    compose:
      enabled: true
      file: infra/docker-compose.yml
      lifecycle-management: start_and_stop  # Sobe ao iniciar, mata ao desligar o App
      readiness:
        wait: ALWAYS # Espera o banco e o rabbit estarem prontos antes de subir o Java

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    api-docs:
      path: /v3/api-docs